### ISSUE TITLE
example notebook still runable?

### ISSUE THREAD

**Issue by kadrlica** [lsst/display_matplotlib#4] opened 2018-07-25 22:01 UTC
Has anyone checked [display_matplotlib.ipynb](../blob/master/examples/display_matplotlib.ipynb)? I'm getting the following error on the Cell 2:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-4d5a75b3ada8> in <module>()
      8 afwMath.randomGaussianImage(im.image, afwMath.Random())
      9 im.setXY0(10, 5)
---> 10 im[0, 0] = 20
     11 im.mask[0, 0] = im.mask.getPlaneBitMask("EDGE")
     12 im[-1, -1] = 30

/opt/lsst/software/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/afw/16.0-19-g2da375352+2/python/lsst/afw/image/slicing.py in __setitem__(self, imageSlice, rhs)
    271                 lhs.set(rhs)
    272         else:
--> 273             self._set(index, origin=origin, value=rhs)
    274     cls.__setitem__ = __setitem__

/opt/lsst/software/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/afw/16.0-19-g2da375352+2/python/lsst/afw/image/maskedImage/maskedImageContinued.py in _set(self, index, value, origin)
     61             Coordinate system of ``index`` (`PARENT` or `LOCAL`).
     62         """
---> 63         self.image[index, origin] = value[0]
     64         self.mask[index, origin] = value[1]
     65         self.variance[index, origin] = value[2]

TypeError: 'int' object is not subscriptable
```

**Comment by RobertLuptonTheGood** [comment] 2018-07-25 22:06
@TallJimbo  changed some of those semantics (I pushed fixes to display_matplotlib yesterday, but didn't catch this).

I'll fix it.

**Comment by kadrlica** [comment] 2018-07-25 22:19
Thanks, saw the PR and thought this might be the case. Here's the (terrible) way I got Cell 2 to run:
```
import lsst.afw.geom as afwGeom
import lsst.afw.image as afwImage
import lsst.afw.math as afwMath

disp = afwDisplay.Display()

im = afwImage.MaskedImageF(100, 50)
afwMath.randomGaussianImage(im.image, afwMath.Random())

x0,y0 = 10,5
im.setXY0(x0, y0)
im.image[x0, y0] = 20
im.mask[x0, y0] = im.mask.getPlaneBitMask("EDGE")
im.image.array[-1,-1] = 30
for x,y in [(50,22),(50,23),(50,24)]:
    im.mask[x,y] = 40
im.mask[50, 22] = 0x5

disp.scale("asinh", "zscale", Q=8)
title="test"
    
disp.mtv(im, title=title)
```
(My knowledge of the LSST image slicing syntax is non-existent...)

**Comment by jdswinbank** [comment] 2018-07-26 16:06
@RobertLuptonTheGood will you file a ticket to handle this work, or would you like me to do it?

**Comment by RobertLuptonTheGood** [comment] 2018-11-12 20:37
From long ago...  The problem is the use of parent or local coordinates (the original used `(0, 0)` to refer to the bottom left physical pixel).  Your solution is fine, or I pushed a different one.

**Closed by RobertLuptonTheGood** 2018-11-12 20:37 UTC
